site_name: Docs Demo
site_author: Louis Maddox
site_description: >-
  Demo site for mkdocs building
site_url: https://docs-pkg.readthedocs.io/
repo_name: lmmx/docs-pkg
repo_url: https://github.com/lmmx/docs-pkg
watch: [src]
strict: true

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2024 Louis Maddox

theme:
  name: material
  palette:
    - scheme: default
      primary: white
  icon:
    repo: fontawesome/brands/github
  features:
    - announce.dismiss
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - search
    - search.suggest
    - toc.follow
  font:
    text: Inter
    code: Source Code Pro

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lmmx
  generator: false

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.definition
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      noclasses: True
      pygments_style: lovelace
  - pymdownx.inlinehilite

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src/*/src/]
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            line_length: 88 # default: 60
            show_if_no_docstring: true
            show_root_heading: true
            # group_by_category: true
            # members: []
            show_source: false
            show_submodules: true
            show_signature_annotations: true
  - search
  - section-index
  - social:
      cards_layout_options:
        color: #173a58

nav:
  - Home:
      - index.md
      - intro/layout.md
      - intro/vercel.md
      - intro/tips.md
  - Usage:
      - User guides: usage/index.md
      - usage/bar.md
      - usage/foo.md
  - API Reference:
      - APIs: api/index.md
      - api/bar.md
      - api/foo.md
